version: '3'
services:
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/user/app
    environment:
      - 'TZ=Asia/Tokyo'
    ports:
      - '4000:4000'
volumes: {}
